import type { ProviderAuthMode, ProviderProtocol } from '../config'

/**
 * Provider presets distilled from the local knowledge base (D:/X/X).
 * These are used only for the direct-HTTP fallback path and as defaults for
 * the plugin's advisor configuration UI. The primary path always goes through
 * DSH's ctx.llm / llm-pi-ai adapter, which reuses the user's existing provider
 * and credential configuration.
 */
export interface ProviderPreset {
  id: string
  label: string
  protocol: ProviderProtocol
  baseURL: string
  apiKeyEnv: string
  defaultModels: string[]
  authMode?: ProviderAuthMode
  /** Optional OpenAI-compatible base URL used for model-list fetching. */
  modelsBaseURL?: string
  modelsAuthMode?: ProviderAuthMode
  notes?: string
}

export const PROVIDER_PRESETS: Record<string, ProviderPreset> = {
  deepseek: {
    id: 'deepseek',
    label: 'DeepSeek',
    protocol: 'openai',
    baseURL: 'https://api.deepseek.com',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    defaultModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
    notes: 'Also available as deepseek-official via dsh-llm-deepseek, and Anthropic-compatible at https://api.deepseek.com/anthropic.',
  },
  'deepseek-anthropic': {
    id: 'deepseek-anthropic',
    label: 'DeepSeek（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://api.deepseek.com/anthropic',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    defaultModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
    authMode: 'x-api-key',
    modelsBaseURL: 'https://api.deepseek.com',
    modelsAuthMode: 'bearer',
    notes: 'DeepSeek Anthropic-compatible endpoint.',
  },
  moonshot: {
    id: 'moonshot',
    label: '月之暗面 Kimi',
    protocol: 'openai',
    baseURL: 'https://api.moonshot.cn/v1',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    defaultModels: ['kimi-k2.6', 'kimi-k2.5'],
    notes: 'OpenAI-compatible; Anthropic-compatible endpoint at https://api.moonshot.cn/anthropic',
  },
  'moonshot-anthropic': {
    id: 'moonshot-anthropic',
    label: '月之暗面 Kimi（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://api.moonshot.cn/anthropic',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    defaultModels: ['kimi-k2.6', 'kimi-k2.5'],
    authMode: 'bearer',
    modelsBaseURL: 'https://api.moonshot.cn/v1',
    modelsAuthMode: 'bearer',
    notes: 'Kimi Anthropic-compatible endpoint; 实际端点 /anthropic/v1/messages（官方 Claude Code 文档）。',
  },
  'kimi-code': {
    id: 'kimi-code',
    label: 'Kimi Code（OpenAI 兼容）',
    protocol: 'openai',
    baseURL: 'https://api.kimi.com/coding/v1',
    apiKeyEnv: 'KIMI_CODE_API_KEY',
    defaultModels: ['k3', 'k3-256k', 'kimi-for-coding', 'kimi-for-coding-highspeed'],
    modelsBaseURL: 'https://api.kimi.com/coding/v1',
    modelsAuthMode: 'bearer',
    notes: 'Kimi Code 会员 API；模型 ID 为 k3 / k3-256k / kimi-for-coding / kimi-for-coding-highspeed。',
  },
  'kimi-code-anthropic': {
    id: 'kimi-code-anthropic',
    label: 'Kimi Code（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://api.kimi.com/coding',
    apiKeyEnv: 'KIMI_CODE_API_KEY',
    defaultModels: ['k3', 'k3-256k', 'kimi-for-coding', 'kimi-for-coding-highspeed'],
    authMode: 'bearer',
    modelsBaseURL: 'https://api.kimi.com/coding/v1',
    modelsAuthMode: 'bearer',
    notes: 'Kimi Code 会员 Anthropic 兼容端点；实际端点 /coding/v1/messages。',
  },
  bailian: {
    id: 'bailian',
    label: '阿里云百炼',
    protocol: 'openai',
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-plus', 'qwen3.7-max', 'qwen-max'],
    notes: 'DashScope OpenAI-compatible endpoint（北京公共域名）。',
  },
  'bailian-openai-singapore': {
    id: 'bailian-openai-singapore',
    label: '阿里云百炼（OpenAI 兼容 · 新加坡公共）',
    protocol: 'openai',
    baseURL: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-plus', 'qwen3.7-max', 'qwen-max'],
    notes: 'DashScope 新加坡公共域名 OpenAI 兼容端点。',
  },
  'bailian-openai-us': {
    id: 'bailian-openai-us',
    label: '阿里云百炼（OpenAI 兼容 · 美国公共）',
    protocol: 'openai',
    baseURL: 'https://dashscope-us.aliyuncs.com/compatible-mode/v1',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-plus', 'qwen3.7-max', 'qwen-max'],
    notes: 'DashScope 美国（弗吉尼亚）公共域名 OpenAI 兼容端点。',
  },
  'bailian-anthropic': {
    id: 'bailian-anthropic',
    label: '阿里云百炼（Anthropic 兼容 · 按量付费 · 业务空间）',
    protocol: 'anthropic',
    baseURL: 'https://{WorkspaceId}.cn-beijing.maas.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: '需要把 {WorkspaceId} 替换为你的百炼业务空间 ID；API Key 为 sk- 开头（按量付费）。',
  },
  'bailian-anthropic-public': {
    id: 'bailian-anthropic-public',
    label: '阿里云百炼（Anthropic 兼容 · 北京公共）',
    protocol: 'anthropic',
    baseURL: 'https://dashscope.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: 'DashScope 北京公共域名 Anthropic 兼容端点。',
  },
  'bailian-anthropic-singapore-public': {
    id: 'bailian-anthropic-singapore-public',
    label: '阿里云百炼（Anthropic 兼容 · 新加坡公共）',
    protocol: 'anthropic',
    baseURL: 'https://dashscope-intl.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: 'DashScope 新加坡公共域名 Anthropic 兼容端点。',
  },
  'bailian-anthropic-us-public': {
    id: 'bailian-anthropic-us-public',
    label: '阿里云百炼（Anthropic 兼容 · 美国公共）',
    protocol: 'anthropic',
    baseURL: 'https://dashscope-us.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope-us.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: 'DashScope 美国（弗吉尼亚）公共域名 Anthropic 兼容端点。',
  },
  'bailian-token-plan-anthropic': {
    id: 'bailian-token-plan-anthropic',
    label: '阿里云百炼（Anthropic 兼容 · Token Plan）',
    protocol: 'anthropic',
    baseURL: 'https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_TOKEN_PLAN_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: 'API Key 为 sk-sp- 开头，必须与 Token Plan Base URL 配套使用。',
  },
  'bailian-coding-plan-anthropic': {
    id: 'bailian-coding-plan-anthropic',
    label: '阿里云百炼（Anthropic 兼容 · Coding Plan）',
    protocol: 'anthropic',
    baseURL: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    apiKeyEnv: 'DASHSCOPE_CODING_PLAN_API_KEY',
    defaultModels: ['qwen3.7-max', 'qwen3.7-plus', 'qwen3.6-plus', 'deepseek-v4-pro', 'deepseek-v4-flash', 'kimi-k2.6', 'glm-5.1'],
    authMode: 'bearer',
    modelsBaseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelsAuthMode: 'bearer',
    notes: 'API Key 为 sk-ws- 开头，必须与 Coding Plan Base URL 配套使用。',
  },
  zhipu: {
    id: 'zhipu',
    label: '智谱 AI',
    protocol: 'openai',
    baseURL: 'https://open.bigmodel.cn/api/paas/v4',
    apiKeyEnv: 'ZHIPU_API_KEY',
    defaultModels: ['glm-5.3', 'glm-5.2', 'glm-5', 'glm-4.6', 'glm-4.6v', 'glm-4.6v-flashx', 'glm-4.5v'],
    modelsBaseURL: 'https://open.bigmodel.cn/api/paas/v4',
    modelsAuthMode: 'bearer',
    notes: '智谱 AI OpenAI 兼容端点；chat completions 为 /v4/chat/completions，模型列表为 /v4/models。',
  },
  'zhipu-anthropic': {
    id: 'zhipu-anthropic',
    label: '智谱 AI（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://open.bigmodel.cn/api/anthropic',
    apiKeyEnv: 'ZHIPU_API_KEY',
    defaultModels: ['glm-5.3', 'glm-5.2', 'glm-5', 'glm-4.6', 'glm-4.6v', 'glm-4.6v-flashx', 'glm-4.5v'],
    authMode: 'bearer',
    modelsBaseURL: 'https://open.bigmodel.cn/api/paas/v4',
    modelsAuthMode: 'bearer',
    notes: '智谱 AI Claude API 兼容端点；ANTHROPIC_BASE_URL=https://open.bigmodel.cn/api/anthropic。',
  },
  openai: {
    id: 'openai',
    label: 'OpenAI',
    protocol: 'openai',
    baseURL: 'https://api.openai.com/v1',
    apiKeyEnv: 'OPENAI_API_KEY',
    defaultModels: ['gpt-5', 'gpt-5-mini'],
    notes: 'Official OpenAI API.',
  },
  anthropic: {
    id: 'anthropic',
    label: 'Claude',
    protocol: 'anthropic',
    baseURL: 'https://api.anthropic.com',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    defaultModels: ['claude-sonnet-4-5', 'claude-opus-4-1'],
    authMode: 'x-api-key',
    notes: 'Anthropic Messages API; docs in D:/X/X/14-claude.',
  },
  gemini: {
    id: 'gemini',
    label: 'Gemini',
    protocol: 'gemini',
    baseURL: 'https://generativelanguage.googleapis.com',
    apiKeyEnv: 'GEMINI_API_KEY',
    defaultModels: ['gemini-3-flash-preview', 'gemini-3-pro-preview'],
    notes: 'Google Gemini API; docs in D:/X/X/13-gemini.',
  },
  siliconflow: {
    id: 'siliconflow',
    label: '硅基流动',
    protocol: 'openai',
    baseURL: 'https://api.siliconflow.cn/v1',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    defaultModels: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen3-235B-A22B'],
    notes: 'OpenAI-compatible; also supports Anthropic-compatible at /v1/messages.',
  },
  'siliconflow-anthropic': {
    id: 'siliconflow-anthropic',
    label: '硅基流动（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://api.siliconflow.cn/v1',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    defaultModels: ['deepseek-ai/DeepSeek-V3.2', 'moonshotai/Kimi-K2-Instruct', 'Qwen/Qwen3-32B'],
    authMode: 'bearer',
    modelsBaseURL: 'https://api.siliconflow.cn/v1',
    modelsAuthMode: 'bearer',
    notes: 'SiliconFlow Anthropic-compatible endpoint: ANTHROPIC_BASE_URL=https://api.siliconflow.cn/ 或 /v1。',
  },
  aihubmix: {
    id: 'aihubmix',
    label: 'AIHubMix',
    protocol: 'openai',
    baseURL: 'https://aihubmix.com/v1',
    apiKeyEnv: 'AIHUBMIX_API_KEY',
    defaultModels: ['gpt-5', 'claude-sonnet-4-5', 'gemini-3-flash-preview'],
    notes: 'Aggregator; also supports Anthropic-compatible at https://aihubmix.com.',
  },
  'aihubmix-anthropic': {
    id: 'aihubmix-anthropic',
    label: 'AIHubMix（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://aihubmix.com',
    apiKeyEnv: 'AIHUBMIX_API_KEY',
    defaultModels: ['claude-sonnet-4-5', 'claude-opus-4-1', 'gpt-5'],
    authMode: 'x-api-key',
    modelsBaseURL: 'https://aihubmix.com/v1',
    modelsAuthMode: 'bearer',
    notes: 'AIHubMix Anthropic-compatible endpoint.',
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    protocol: 'openai',
    baseURL: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    defaultModels: ['openai/gpt-5', 'anthropic/claude-sonnet-4.5', 'deepseek/deepseek-chat'],
    notes: 'OpenAI-compatible; docs in D:/X/X/06-OpenRouter.',
  },
  'openrouter-anthropic': {
    id: 'openrouter-anthropic',
    label: 'OpenRouter（Anthropic 兼容）',
    protocol: 'anthropic',
    baseURL: 'https://openrouter.ai/api',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    defaultModels: ['anthropic/claude-sonnet-4.5', 'anthropic/claude-opus-4-1', 'openai/gpt-5', 'deepseek/deepseek-chat'],
    authMode: 'bearer',
    modelsBaseURL: 'https://openrouter.ai/api/v1',
    modelsAuthMode: 'bearer',
    notes: 'OpenRouter Anthropic Skin；使用 ANTHROPIC_BASE_URL=https://openrouter.ai/api + ANTHROPIC_AUTH_TOKEN=OpenRouter Key（Bearer）。',
  },
}

export function getProviderPreset(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS[id]
}
